# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

### Test root endpoint
GET http://127.0.0.1:8000/

### Test hello endpoint
GET http://127.0.0.1:8000/hello/Harsha
